import type { MyzelBallMode, MyzelNodeMode } from "../../resonance/myceliumInterpreters";
import type { Room3BodyControls } from "../../resonance/timbreModel";
import { createEmptyOvertoneMix } from "./instrumentData";
import type {
  BassPattern,
  ChurchMode,
  DronePreset,
  DrumKit,
  DrumPattern,
  GridTuning,
  MyzelPattern,
  ParticleGradientPreset,
  ParticlePreset,
  QuantizeGrid,
  WaveDecayPreset,
  WaveOvertoneWaveform,
  WaveSoundPreset,
  WaveTimbreGradientPreset,
  WaveVolumeGradientPreset,
  ParticleSystem,
} from "./instrumentData";

export type MetaPresetId = "north" | "northEast" | "east" | "southEast" | "south" | "southWest" | "west" | "northWest";

type SourceSendConfig = { enabled?: boolean; send?: number };
type MemorySourceConfig = SourceSendConfig & { wet?: number };

export interface MetaPresetDefinition {
  id: MetaPresetId;
  label: string;
  description: string;
  points: string;
  dronePreset: DronePreset;
  particlePreset: ParticlePreset;
  waveSoundPreset: WaveSoundPreset;
  waveSoundEnabled?: boolean;
  waveSoundVolume?: number;
  droneVolume?: number;
  quantizeGrid?: QuantizeGrid;
  gridTempoBpm?: number;
  myzelEnabled?: boolean;
  myzelPattern?: MyzelPattern;
  myzelBallMode?: MyzelBallMode;
  myzelNodeMode?: MyzelNodeMode;
  myzelStep16ths?: number;
  tParams?: { tension: number; slimLayers: number; rawReality: number; intensityGlobal: number };
  room3Body?: {
    enabled?: boolean;
    controls?: Partial<Room3BodyControls>;
  };
  collectiveMemory?: {
    enabled?: boolean;
    window?: number;
    drone?: MemorySourceConfig;
    particles?: MemorySourceConfig;
    waves?: MemorySourceConfig;
    myzel?: MemorySourceConfig;
  };
  spiral?: {
    enabled?: boolean;
    follow?: number;
    drive?: number;
    color?: number;
    motion?: number;
    feedback?: number;
    bloom?: number;
    mix?: number;
    stereoWidth?: number;
    outputGain?: number;
    drone?: SourceSendConfig;
    particles?: SourceSendConfig;
    waves?: SourceSendConfig;
    myzel?: SourceSendConfig;
  };
  liveMastering?: {
    enabled?: boolean;
    strength?: number;
    glue?: number;
    air?: number;
  };
  transientDrive?: {
    drone?: SourceSendConfig;
    particles?: SourceSendConfig;
    waves?: SourceSendConfig;
    myzel?: SourceSendConfig;
  };
  nexusPatch?: Partial<{
    echoOn: boolean;
    echoTempo: number;
    echoDecay: number;
    waveRadius: number;
    waveDecay: WaveDecayPreset;
    gridOn: boolean;
    gridBase: number;
    gridTuning: GridTuning;
    gridMode: ChurchMode;
    particleSystem: ParticleSystem;
    churchMode: ChurchMode;
    lockCursorToGrid: boolean;
    cursorSpeed: number;
    droneTimbre: number;
    droneVibrato: number;
    droneFlanger: number;
    droneRhythm: string;
    droneDriveOn: boolean;
    droneDriveAmount: number;
    droneDriveTone: number;
    droneDriveMix: number;
    droneDriveOutput: number;
    drumActive: boolean;
    drumPattern: DrumPattern;
    drumKit: DrumKit;
    drumVolume: number;
    bassActive: boolean;
    bassPattern: BassPattern;
    bassVolume: number;
    bassRootMode: "auto" | "fixed";
    bassRootHz: number;
    particleGradientX: ParticleGradientPreset;
    particleGradientY: ParticleGradientPreset;
    waveTimbreGradientEnabled: boolean;
    waveTimbreGradientX: WaveTimbreGradientPreset;
    waveVolumeGradientEnabled: boolean;
    waveVolumeGradientX: WaveVolumeGradientPreset;
    waveOvertonesEnabled: boolean;
    droneOvertoneWaveform: WaveOvertoneWaveform;
    waveOvertoneWaveform: WaveOvertoneWaveform;
    particleVolume: number;
    particleMute: boolean;
    quantizeOn: boolean;
    quantizeBpm: number;
  }>;
  gridAllowedSteps?: number[];
  gridOffsets?: Record<number, number>;
  agentEnabledSteps?: number[];
  agentVolumes?: Record<number, number>;
  droneOvertones?: Partial<Record<string, number>>;
  waveOvertones?: Partial<Record<string, number>>;
}

export const createMetaOvertoneMix = (partial: Partial<Record<string, number>> = {}): Record<string, number> => ({
  ...createEmptyOvertoneMix(),
  ...Object.fromEntries(Object.entries(partial).filter(([, value]) => typeof value === "number")) as Record<string, number>,
});

export const META_PRESETS: MetaPresetDefinition[] = [
  {
    id: "north",
    label: "Spannungskrone",
    description: "31-EDO-Spannungsfeld mit Funkenpartikeln, metallischem Körper und knackigem Staubschritt.",
    points: "0,-48 9,-38 -9,-38",
    dronePreset: "bronze_reed",
    particlePreset: "granular_spark",
    waveSoundPreset: "spark_chime",
    waveSoundEnabled: true,
    waveSoundVolume: 0.27,
    droneVolume: 0.12,
    quantizeGrid: 16,
    gridTempoBpm: 116,
    myzelEnabled: true,
    myzelPattern: "spiral",
    myzelBallMode: "pressure",
    myzelNodeMode: "field",
    myzelStep16ths: 2,
    tParams: { tension: 0.88, slimLayers: 0.42, rawReality: 0.62, intensityGlobal: 0.84 },
    room3Body: { enabled: true, controls: { coupling: 0.82, material: 0.84, air: 0.26, roughness: 0.74, resonance: 0.7 } },
    collectiveMemory: {
      enabled: true,
      window: 6.8,
      drone: { enabled: true, send: 0.14, wet: 0.08 },
      particles: { enabled: true, send: 0.22, wet: 0.09 },
      waves: { enabled: true, send: 0.2, wet: 0.08 },
      myzel: { enabled: true, send: 0.3, wet: 0.18 },
    },
    spiral: {
      enabled: true,
      follow: 0.58,
      drive: 0.52,
      color: 0.7,
      motion: 0.46,
      feedback: 0.3,
      bloom: 0.4,
      mix: 0.52,
      stereoWidth: 0.82,
      outputGain: 0.86,
      drone: { enabled: true, send: 0.08 },
      particles: { enabled: true, send: 0.2 },
      waves: { enabled: true, send: 0.24 },
      myzel: { enabled: true, send: 0.22 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.34 },
      waves: { enabled: true, send: 0.38 },
      myzel: { enabled: true, send: 0.1 },
    },
    liveMastering: { enabled: false, strength: 0.58, glue: 0.48, air: 0.46 },
    nexusPatch: {
      gridTuning: "31edo",
      gridMode: "lydian",
      particleSystem: "ji",
      churchMode: "chromatic",
      droneTimbre: 0.78,
      droneVibrato: 0.18,
      droneFlanger: 0.42,
      droneRhythm: "Synkope",
      droneDriveOn: true,
      droneDriveAmount: 0.42,
      droneDriveTone: 0.62,
      droneDriveMix: 0.18,
      droneDriveOutput: 0.82,
      drumActive: true,
      drumPattern: "duststep",
      drumKit: "glass_metal",
      drumVolume: 0.44,
      bassActive: true,
      bassPattern: "arpeggio",
      bassVolume: 0.3,
      bassRootMode: "auto",
      particleGradientX: "metal_max",
      particleGradientY: "edge_spark",
      waveOvertonesEnabled: true,
      droneOvertoneWaveform: "triangle",
      waveOvertoneWaveform: "triangle",
      particleVolume: 0.19,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 0.98,
      waveDecay: "exponential",
      echoOn: false,
      echoTempo: 330,
      echoDecay: 0.34,
    },
    gridAllowedSteps: [0, 5, 10, 13, 18, 23, 26, 30],
    gridOffsets: { 10: 3, 13: 8, 18: -6, 23: 4, 26: -10, 30: -14 },
    agentEnabledSteps: [0, 2, 3, 4, 5, 6, 8, 10, 11],
    agentVolumes: { 0: 0.95, 2: 0.78, 3: 0.7, 4: 0.76, 5: 1.12, 6: 1.18, 8: 0.92, 10: 1.04, 11: 0.8 },
    droneOvertones: createMetaOvertoneMix({ "3/2": 0.62, "11/8": 0.52, "13/8": 0.46, "7/4": 0.38, "15/8": 0.28 }),
    waveOvertones: createMetaOvertoneMix({ "11/8": 0.58, "13/8": 0.48, "3/2": 0.32, "7/4": 0.22 }),
  },
  {
    id: "northEast",
    label: "Lambda-Schleier",
    description: "Bohlen-Pierce-Schleier aus Reeds, Glasbogen und leicht taumelnder Spiral-Luft.",
    points: "31,-31 20,-31 31,-20",
    dronePreset: "glass_pipe",
    particlePreset: "reed_pop",
    waveSoundPreset: "bowed_glass",
    waveSoundEnabled: true,
    waveSoundVolume: 0.24,
    droneVolume: 0.1,
    quantizeGrid: 32,
    gridTempoBpm: 102,
    myzelEnabled: true,
    myzelPattern: "choir",
    myzelBallMode: "orbit",
    myzelNodeMode: "hybrid",
    myzelStep16ths: 3,
    tParams: { tension: 0.7, slimLayers: 0.68, rawReality: 0.24, intensityGlobal: 0.72 },
    room3Body: { enabled: true, controls: { coupling: 0.74, material: 0.9, air: 0.52, roughness: 0.32, resonance: 0.82 } },
    collectiveMemory: {
      enabled: true,
      window: 8.4,
      drone: { enabled: true, send: 0.12, wet: 0.07 },
      particles: { enabled: true, send: 0.16, wet: 0.08 },
      waves: { enabled: true, send: 0.24, wet: 0.12 },
      myzel: { enabled: true, send: 0.3, wet: 0.18 },
    },
    spiral: {
      enabled: true,
      follow: 0.64,
      drive: 0.32,
      color: 0.74,
      motion: 0.62,
      feedback: 0.34,
      bloom: 0.58,
      mix: 0.62,
      stereoWidth: 0.9,
      outputGain: 0.88,
      drone: { enabled: true, send: 0.06 },
      particles: { enabled: true, send: 0.16 },
      waves: { enabled: true, send: 0.28 },
      myzel: { enabled: true, send: 0.26 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.16 },
      waves: { enabled: true, send: 0.22 },
      myzel: { enabled: false, send: 0.04 },
    },
    liveMastering: { enabled: false, strength: 0.52, glue: 0.46, air: 0.54 },
    nexusPatch: {
      gridTuning: "bp",
      gridMode: "bp_lambda",
      particleSystem: "12edo",
      churchMode: "phrygian",
      droneTimbre: 0.62,
      droneVibrato: 0.48,
      droneFlanger: 0.42,
      droneRhythm: "Puls 1/8",
      droneDriveOn: true,
      droneDriveAmount: 0.24,
      droneDriveTone: 0.7,
      droneDriveMix: 0.1,
      droneDriveOutput: 0.82,
      drumActive: true,
      drumPattern: "broken_lilt",
      drumKit: "dusty_tape",
      drumVolume: 0.36,
      bassActive: true,
      bassPattern: "walking",
      bassVolume: 0.26,
      bassRootMode: "auto",
      particleGradientX: "bright_min",
      particleGradientY: "warm_center",
      waveOvertonesEnabled: true,
      droneOvertoneWaveform: "square",
      waveOvertoneWaveform: "triangle",
      particleVolume: 0.16,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 1.16,
      waveDecay: "bellcurve",
      echoOn: true,
      echoTempo: 420,
      echoDecay: 0.42,
    },
    gridAllowedSteps: [0, 2, 3, 4, 6, 7, 9, 10, 12],
    gridOffsets: { 4: 12, 7: -8, 10: 7 },
    agentEnabledSteps: [0, 1, 3, 5, 7, 8, 10],
    agentVolumes: { 0: 0.95, 1: 0.86, 3: 0.82, 5: 0.72, 7: 0.98, 8: 0.86, 10: 0.72 },
    droneOvertones: createMetaOvertoneMix({ "9/8": 0.42, "11/8": 0.46, "13/8": 0.58, "15/8": 0.28, "7/4": 0.2 }),
    waveOvertones: createMetaOvertoneMix({ "11/8": 0.42, "13/8": 0.62, "15/8": 0.34, "3/2": 0.18 }),
  },
  {
    id: "east",
    label: "Glasgitter",
    description: "Luftiges 19-EDO-Glasfeld mit Staubglocken, Bogenwellen und hellem Nachraum.",
    points: "48,0 38,-9 38,9",
    dronePreset: "glass_pipe",
    particlePreset: "dust_chime",
    waveSoundPreset: "bowed_glass",
    waveSoundEnabled: true,
    waveSoundVolume: 0.28,
    droneVolume: 0.08,
    quantizeGrid: 16,
    gridTempoBpm: 108,
    myzelEnabled: true,
    myzelPattern: "breath",
    myzelBallMode: "scanner",
    myzelNodeMode: "hybrid",
    myzelStep16ths: 4,
    tParams: { tension: 0.46, slimLayers: 0.78, rawReality: 0.18, intensityGlobal: 0.56 },
    room3Body: { enabled: true, controls: { coupling: 0.68, material: 0.94, air: 0.62, roughness: 0.18, resonance: 0.86 } },
    collectiveMemory: {
      enabled: true,
      window: 9.2,
      drone: { enabled: false, send: 0, wet: 0 },
      particles: { enabled: true, send: 0.18, wet: 0.08 },
      waves: { enabled: true, send: 0.22, wet: 0.1 },
      myzel: { enabled: true, send: 0.22, wet: 0.14 },
    },
    spiral: {
      enabled: true,
      follow: 0.52,
      drive: 0.2,
      color: 0.68,
      motion: 0.46,
      feedback: 0.2,
      bloom: 0.52,
      mix: 0.44,
      stereoWidth: 0.94,
      outputGain: 0.86,
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.12 },
      waves: { enabled: true, send: 0.18 },
      myzel: { enabled: true, send: 0.16 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.14 },
      waves: { enabled: true, send: 0.12 },
      myzel: { enabled: false, send: 0.04 },
    },
    liveMastering: { enabled: false, strength: 0.48, glue: 0.42, air: 0.58 },
    nexusPatch: {
      gridTuning: "19edo",
      gridMode: "lydian",
      particleSystem: "ji",
      churchMode: "ionian",
      droneTimbre: 0.54,
      droneVibrato: 0.6,
      droneFlanger: 0.28,
      droneRhythm: "Off",
      droneDriveOn: false,
      droneDriveAmount: 0.18,
      droneDriveTone: 0.62,
      droneDriveMix: 0.06,
      droneDriveOutput: 0.82,
      drumActive: true,
      drumPattern: "broken_lilt",
      drumKit: "glass_metal",
      drumVolume: 0.24,
      bassActive: true,
      bassPattern: "offbeat",
      bassVolume: 0.2,
      bassRootMode: "auto",
      particleGradientX: "bright_max",
      particleGradientY: "edge_spark",
      waveOvertonesEnabled: true,
      droneOvertoneWaveform: "sine",
      waveOvertoneWaveform: "triangle",
      particleVolume: 0.17,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 1.26,
      waveDecay: "bellcurve",
      echoOn: true,
      echoTempo: 500,
      echoDecay: 0.4,
    },
    gridOffsets: { 6: 6, 12: -4 },
    agentEnabledSteps: [0, 3, 4, 6, 9, 11],
    agentVolumes: { 0: 0.86, 3: 1.02, 4: 0.8, 6: 1.12, 9: 0.74, 11: 0.68 },
    droneOvertones: createMetaOvertoneMix({ "15/8": 0.42, "13/8": 0.34, "11/8": 0.22, "3/2": 0.22 }),
    waveOvertones: createMetaOvertoneMix({ "15/8": 0.56, "13/8": 0.48, "5/4": 0.26 }),
  },
  {
    id: "southEast",
    label: "Rohrdrift",
    description: "17-EDO-Holzrohr mit Reed-Pops, Seufzerwellen und bewegter Membranbox.",
    points: "31,31 20,31 31,20",
    dronePreset: "dust_bow",
    particlePreset: "reed_pop",
    waveSoundPreset: "reed_sigh",
    waveSoundEnabled: true,
    waveSoundVolume: 0.24,
    droneVolume: 0.11,
    quantizeGrid: 16,
    gridTempoBpm: 98,
    myzelEnabled: true,
    myzelPattern: "breath",
    myzelBallMode: "orbit",
    myzelNodeMode: "ji",
    myzelStep16ths: 5,
    tParams: { tension: 0.44, slimLayers: 0.66, rawReality: 0.34, intensityGlobal: 0.54 },
    room3Body: { enabled: true, controls: { coupling: 0.7, material: 0.44, air: 0.24, roughness: 0.36, resonance: 0.74 } },
    collectiveMemory: {
      enabled: true,
      window: 7.2,
      drone: { enabled: false, send: 0, wet: 0 },
      particles: { enabled: true, send: 0.12, wet: 0.06 },
      waves: { enabled: true, send: 0.16, wet: 0.08 },
      myzel: { enabled: true, send: 0.22, wet: 0.12 },
    },
    spiral: {
      enabled: false,
      follow: 0.38,
      drive: 0.22,
      color: 0.48,
      motion: 0.32,
      feedback: 0.18,
      bloom: 0.22,
      mix: 0.26,
      stereoWidth: 0.72,
      outputGain: 0.88,
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.06 },
      waves: { enabled: true, send: 0.08 },
      myzel: { enabled: true, send: 0.08 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.22 },
      waves: { enabled: true, send: 0.26 },
      myzel: { enabled: false, send: 0.06 },
    },
    liveMastering: { enabled: false, strength: 0.52, glue: 0.5, air: 0.42 },
    nexusPatch: {
      gridTuning: "17edo",
      gridMode: "dorian",
      particleSystem: "12edo",
      churchMode: "mixolydian",
      droneTimbre: 0.48,
      droneVibrato: 0.18,
      droneFlanger: 0.16,
      droneRhythm: "Puls 1/4",
      droneDriveOn: true,
      droneDriveAmount: 0.24,
      droneDriveTone: 0.48,
      droneDriveMix: 0.1,
      droneDriveOutput: 0.84,
      drumActive: true,
      drumPattern: "broken_lilt",
      drumKit: "membrane_box",
      drumVolume: 0.36,
      bassActive: true,
      bassPattern: "walking",
      bassVolume: 0.28,
      bassRootMode: "auto",
      particleGradientX: "wood_min",
      particleGradientY: "warm_center",
      waveOvertonesEnabled: false,
      droneOvertoneWaveform: "triangle",
      waveOvertoneWaveform: "triangle",
      particleVolume: 0.17,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 1.06,
      waveDecay: "linear",
      echoOn: false,
      echoTempo: 360,
      echoDecay: 0.26,
    },
    agentEnabledSteps: [0, 2, 4, 5, 7, 9, 10],
    agentVolumes: { 0: 0.9, 2: 0.7, 4: 0.82, 5: 0.72, 7: 1.02, 9: 0.8, 10: 0.74 },
    droneOvertones: createMetaOvertoneMix({ "6/5": 0.34, "4/3": 0.46, "3/2": 0.52, "7/4": 0.2 }),
    waveOvertones: createMetaOvertoneMix({}),
  },
  {
    id: "south",
    label: "Warmer Boden",
    description: "Breiter Ruheboden aus Staubglocken, Tape-Halo und weicher Begleitung ganz hinten.",
    points: "0,48 -9,38 9,38",
    dronePreset: "membrane_bloom",
    particlePreset: "dust_chime",
    waveSoundPreset: "tape_halo",
    waveSoundEnabled: true,
    waveSoundVolume: 0.22,
    droneVolume: 0.06,
    quantizeGrid: 16,
    gridTempoBpm: 90,
    myzelEnabled: true,
    myzelPattern: "breath",
    myzelBallMode: "scanner",
    myzelNodeMode: "ji",
    myzelStep16ths: 6,
    tParams: { tension: 0.26, slimLayers: 0.84, rawReality: 0.16, intensityGlobal: 0.42 },
    room3Body: { enabled: true, controls: { coupling: 0.62, material: 0.28, air: 0.36, roughness: 0.12, resonance: 0.68 } },
    collectiveMemory: {
      enabled: true,
      window: 8.6,
      drone: { enabled: false, send: 0, wet: 0 },
      particles: { enabled: true, send: 0.14, wet: 0.08 },
      waves: { enabled: true, send: 0.18, wet: 0.1 },
      myzel: { enabled: true, send: 0.18, wet: 0.12 },
    },
    spiral: {
      enabled: false,
      follow: 0.34,
      drive: 0.18,
      color: 0.46,
      motion: 0.26,
      feedback: 0.12,
      bloom: 0.2,
      mix: 0.18,
      stereoWidth: 0.7,
      outputGain: 0.88,
      drone: { enabled: false, send: 0 },
      particles: { enabled: false, send: 0.02 },
      waves: { enabled: true, send: 0.04 },
      myzel: { enabled: false, send: 0.04 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: false, send: 0.08 },
      waves: { enabled: true, send: 0.1 },
      myzel: { enabled: false, send: 0.04 },
    },
    liveMastering: { enabled: false, strength: 0.46, glue: 0.42, air: 0.36 },
    nexusPatch: {
      gridTuning: "12edo",
      gridMode: "ionian",
      particleSystem: "ji",
      churchMode: "ionian",
      droneTimbre: 0.34,
      droneVibrato: 0.14,
      droneFlanger: 0.08,
      droneRhythm: "Off",
      droneDriveOn: false,
      droneDriveAmount: 0.14,
      droneDriveTone: 0.44,
      droneDriveMix: 0.04,
      droneDriveOutput: 0.8,
      drumActive: true,
      drumPattern: "broken_lilt",
      drumKit: "dusty_tape",
      drumVolume: 0.22,
      bassActive: true,
      bassPattern: "offbeat",
      bassVolume: 0.2,
      bassRootMode: "auto",
      particleGradientX: "warm_center",
      particleGradientY: "warm_center",
      waveOvertonesEnabled: false,
      droneOvertoneWaveform: "triangle",
      waveOvertoneWaveform: "triangle",
      particleVolume: 0.16,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 1.32,
      waveDecay: "late_falloff",
      echoOn: true,
      echoTempo: 560,
      echoDecay: 0.34,
    },
    agentEnabledSteps: [0, 3, 4, 6, 9, 11],
    agentVolumes: { 0: 0.82, 3: 0.96, 4: 0.74, 6: 1.04, 9: 0.64, 11: 0.56 },
    droneOvertones: createMetaOvertoneMix({ "5/4": 0.34, "3/2": 0.42, "4/3": 0.3, "5/3": 0.18 }),
    waveOvertones: createMetaOvertoneMix({}),
  },
  {
    id: "southWest",
    label: "Tiefe Spule",
    description: "Gedämpftes Unterholz mit Membran-Schlägen, Gummiclicks und dunklem JI-Schatten.",
    points: "-31,31 -20,31 -31,20",
    dronePreset: "dark_sub",
    particlePreset: "rubber_click",
    waveSoundPreset: "membrane_thump",
    waveSoundEnabled: true,
    waveSoundVolume: 0.2,
    droneVolume: 0.08,
    quantizeGrid: 16,
    gridTempoBpm: 90,
    myzelEnabled: true,
    myzelPattern: "odd_bloom",
    myzelBallMode: "pressure",
    myzelNodeMode: "field",
    myzelStep16ths: 3,
    tParams: { tension: 0.66, slimLayers: 0.5, rawReality: 0.66, intensityGlobal: 0.68 },
    room3Body: { enabled: true, controls: { coupling: 0.78, material: 0.14, air: 0.18, roughness: 0.58, resonance: 0.62 } },
    collectiveMemory: {
      enabled: true,
      window: 5.6,
      drone: { enabled: false, send: 0, wet: 0 },
      particles: { enabled: true, send: 0.08, wet: 0.04 },
      waves: { enabled: true, send: 0.1, wet: 0.05 },
      myzel: { enabled: true, send: 0.2, wet: 0.1 },
    },
    spiral: {
      enabled: false,
      follow: 0.42,
      drive: 0.28,
      color: 0.38,
      motion: 0.24,
      feedback: 0.14,
      bloom: 0.18,
      mix: 0.16,
      stereoWidth: 0.64,
      outputGain: 0.86,
      drone: { enabled: false, send: 0 },
      particles: { enabled: false, send: 0.04 },
      waves: { enabled: false, send: 0.04 },
      myzel: { enabled: false, send: 0.04 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.28 },
      waves: { enabled: true, send: 0.32 },
      myzel: { enabled: false, send: 0.08 },
    },
    liveMastering: { enabled: false, strength: 0.54, glue: 0.5, air: 0.34 },
    nexusPatch: {
      gridTuning: "ji",
      gridMode: "aeolian",
      particleSystem: "ji",
      churchMode: "aeolian",
      droneTimbre: 0.58,
      droneVibrato: 0.08,
      droneFlanger: 0.12,
      droneRhythm: "Puls 1/16",
      droneDriveOn: true,
      droneDriveAmount: 0.32,
      droneDriveTone: 0.36,
      droneDriveMix: 0.1,
      droneDriveOutput: 0.82,
      drumActive: true,
      drumPattern: "duststep",
      drumKit: "membrane_box",
      drumVolume: 0.34,
      bassActive: true,
      bassPattern: "stotter",
      bassVolume: 0.28,
      bassRootMode: "auto",
      particleGradientX: "none",
      particleGradientY: "wood_min",
      waveOvertonesEnabled: false,
      droneOvertoneWaveform: "sine",
      waveOvertoneWaveform: "sine",
      particleVolume: 0.14,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 0.9,
      waveDecay: "abrupt",
      echoOn: false,
      echoTempo: 320,
      echoDecay: 0.2,
    },
    agentEnabledSteps: [0, 2, 4, 6, 10, 11],
    agentVolumes: { 0: 0.9, 2: 0.72, 4: 0.8, 6: 0.9, 10: 0.64, 11: 0.48 },
    droneOvertones: createMetaOvertoneMix({ "4/3": 0.34, "3/2": 0.22, "6/5": 0.18, "7/4": 0.16 }),
    waveOvertones: createMetaOvertoneMix({}),
  },
  {
    id: "west",
    label: "Metallblüte",
    description: "Schroffe 22-EDO-Winkel mit Metallkorpus, Funkensalven und gläsernem Kit.",
    points: "-48,0 -38,9 -38,-9",
    dronePreset: "metallic",
    particlePreset: "granular_spark",
    waveSoundPreset: "spark_chime",
    waveSoundEnabled: true,
    waveSoundVolume: 0.26,
    droneVolume: 0.12,
    quantizeGrid: 16,
    gridTempoBpm: 118,
    myzelEnabled: true,
    myzelPattern: "spiral",
    myzelBallMode: "pressure",
    myzelNodeMode: "field",
    myzelStep16ths: 2,
    tParams: { tension: 0.8, slimLayers: 0.38, rawReality: 0.5, intensityGlobal: 0.82 },
    room3Body: { enabled: true, controls: { coupling: 0.84, material: 0.88, air: 0.3, roughness: 0.68, resonance: 0.76 } },
    collectiveMemory: {
      enabled: true,
      window: 6.4,
      drone: { enabled: true, send: 0.1, wet: 0.06 },
      particles: { enabled: true, send: 0.18, wet: 0.07 },
      waves: { enabled: true, send: 0.18, wet: 0.07 },
      myzel: { enabled: true, send: 0.24, wet: 0.14 },
    },
    spiral: {
      enabled: true,
      follow: 0.56,
      drive: 0.44,
      color: 0.66,
      motion: 0.5,
      feedback: 0.26,
      bloom: 0.34,
      mix: 0.42,
      stereoWidth: 0.82,
      outputGain: 0.88,
      drone: { enabled: true, send: 0.08 },
      particles: { enabled: true, send: 0.18 },
      waves: { enabled: true, send: 0.2 },
      myzel: { enabled: true, send: 0.16 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.34 },
      waves: { enabled: true, send: 0.36 },
      myzel: { enabled: true, send: 0.08 },
    },
    liveMastering: { enabled: false, strength: 0.56, glue: 0.5, air: 0.5 },
    nexusPatch: {
      gridTuning: "22edo",
      gridMode: "phrygian",
      particleSystem: "bp",
      churchMode: "bp_minor",
      droneTimbre: 0.72,
      droneVibrato: 0.22,
      droneFlanger: 0.46,
      droneRhythm: "Synkope",
      droneDriveOn: true,
      droneDriveAmount: 0.46,
      droneDriveTone: 0.58,
      droneDriveMix: 0.14,
      droneDriveOutput: 0.84,
      drumActive: true,
      drumPattern: "duststep",
      drumKit: "glass_metal",
      drumVolume: 0.42,
      bassActive: true,
      bassPattern: "arpeggio",
      bassVolume: 0.3,
      bassRootMode: "auto",
      particleGradientX: "metal_max",
      particleGradientY: "bright_min",
      waveOvertonesEnabled: true,
      droneOvertoneWaveform: "sawtooth",
      waveOvertoneWaveform: "triangle",
      particleVolume: 0.19,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 1,
      waveDecay: "exponential",
      echoOn: false,
      echoTempo: 350,
      echoDecay: 0.3,
    },
    gridOffsets: { 5: 8, 12: -6, 17: 10 },
    agentEnabledSteps: [0, 1, 3, 5, 6, 8, 9, 11, 12],
    agentVolumes: { 0: 0.88, 1: 0.74, 3: 0.8, 5: 0.92, 6: 0.8, 8: 1.08, 9: 0.76, 11: 0.92, 12: 0.64 },
    droneOvertones: createMetaOvertoneMix({ "11/8": 0.56, "13/8": 0.56, "7/4": 0.38, "3/2": 0.22, "9/8": 0.18 }),
    waveOvertones: createMetaOvertoneMix({ "11/8": 0.46, "13/8": 0.54, "7/4": 0.22 }),
  },
  {
    id: "northWest",
    label: "Bandfünften",
    description: "Weiche Tape-Färbung mit offenen Quinten, Halo-Wellen und staubigen Begleitpartikeln.",
    points: "-31,-31 -20,-31 -31,-20",
    dronePreset: "fjord_tape",
    particlePreset: "dust_chime",
    waveSoundPreset: "tape_halo",
    waveSoundEnabled: true,
    waveSoundVolume: 0.24,
    droneVolume: 0.09,
    quantizeGrid: 16,
    gridTempoBpm: 96,
    myzelEnabled: true,
    myzelPattern: "choir",
    myzelBallMode: "orbit",
    myzelNodeMode: "hybrid",
    myzelStep16ths: 4,
    tParams: { tension: 0.48, slimLayers: 0.72, rawReality: 0.28, intensityGlobal: 0.58 },
    room3Body: { enabled: true, controls: { coupling: 0.68, material: 0.34, air: 0.4, roughness: 0.2, resonance: 0.68 } },
    collectiveMemory: {
      enabled: true,
      window: 8.2,
      drone: { enabled: false, send: 0, wet: 0 },
      particles: { enabled: true, send: 0.16, wet: 0.08 },
      waves: { enabled: true, send: 0.22, wet: 0.12 },
      myzel: { enabled: true, send: 0.2, wet: 0.12 },
    },
    spiral: {
      enabled: true,
      follow: 0.44,
      drive: 0.22,
      color: 0.52,
      motion: 0.36,
      feedback: 0.2,
      bloom: 0.3,
      mix: 0.28,
      stereoWidth: 0.8,
      outputGain: 0.9,
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.08 },
      waves: { enabled: true, send: 0.12 },
      myzel: { enabled: true, send: 0.12 },
    },
    transientDrive: {
      drone: { enabled: false, send: 0 },
      particles: { enabled: true, send: 0.12 },
      waves: { enabled: true, send: 0.16 },
      myzel: { enabled: false, send: 0.04 },
    },
    liveMastering: { enabled: false, strength: 0.5, glue: 0.46, air: 0.4 },
    nexusPatch: {
      gridTuning: "ji",
      gridMode: "mixolydian",
      particleSystem: "12edo",
      churchMode: "dorian",
      droneTimbre: 0.52,
      droneVibrato: 0.28,
      droneFlanger: 0.2,
      droneRhythm: "Off",
      droneDriveOn: false,
      droneDriveAmount: 0.18,
      droneDriveTone: 0.52,
      droneDriveMix: 0.06,
      droneDriveOutput: 0.84,
      drumActive: true,
      drumPattern: "broken_lilt",
      drumKit: "dusty_tape",
      drumVolume: 0.28,
      bassActive: true,
      bassPattern: "offbeat",
      bassVolume: 0.24,
      bassRootMode: "auto",
      particleGradientX: "warm_center",
      particleGradientY: "bright_min",
      waveOvertonesEnabled: true,
      droneOvertoneWaveform: "triangle",
      waveOvertoneWaveform: "sine",
      particleVolume: 0.16,
      particleMute: false,
      quantizeOn: false,
      waveRadius: 1.18,
      waveDecay: "late_falloff",
      echoOn: true,
      echoTempo: 510,
      echoDecay: 0.4,
    },
    agentEnabledSteps: [0, 2, 3, 5, 7, 9, 10],
    agentVolumes: { 0: 0.88, 2: 0.76, 3: 0.82, 5: 0.74, 7: 1, 9: 0.72, 10: 0.66 },
    droneOvertones: createMetaOvertoneMix({ "4/3": 0.34, "3/2": 0.42, "5/3": 0.24, "6/5": 0.2, "15/8": 0.16 }),
    waveOvertones: createMetaOvertoneMix({ "4/3": 0.22, "3/2": 0.3, "5/3": 0.22 }),
  },
];
