import type { DrumKit, DrumPattern } from "../xensonar/domain/instrumentData";
import { getStaticDrumStepTriggers } from "../xensonar/drumPatternMachine";

export type DrumVoice = "kick" | "snare" | "hat_closed" | "hat_open" | "clap" | "perc";

export interface DrumStyle {
  edge: number;
  softness: number;
  air: number;
  snap: number;
  swing: number;
}

export const DEFAULT_DRUM_STYLE: DrumStyle = { edge: 0.46, softness: 0.58, air: 0.5, snap: 0.48, swing: 0.38 };

export interface DrumMachine {
  trigger: (voice: DrumVoice, time: number, level: number, kit: DrumKit, style?: Partial<DrumStyle>) => void;
  schedulePattern: (pattern: DrumPattern, step: number, time: number, level: number, kit: DrumKit, style?: Partial<DrumStyle>) => void;
}

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
const KIT_PROFILE: Record<DrumKit, { kickPitchStart:number; kickPitchEnd:number; kickDecay:number; kickDrive:number; snareToneHz:number; snareNoiseHz:number; hatHz:number; hatDecay:number; noiseColor:number; percRatio:number; }> = {
  dusty_tape: { kickPitchStart:128, kickPitchEnd:38, kickDecay:0.18, kickDrive:1.7, snareToneHz:180, snareNoiseHz:2400, hatHz:7600, hatDecay:0.075, noiseColor:0.85, percRatio:1.33 },
  membrane_box: { kickPitchStart:112, kickPitchEnd:30, kickDecay:0.22, kickDrive:1.4, snareToneHz:208, snareNoiseHz:2100, hatHz:6900, hatDecay:0.09, noiseColor:0.72, percRatio:1.18 },
  glass_metal: { kickPitchStart:142, kickPitchEnd:48, kickDecay:0.14, kickDrive:2.1, snareToneHz:250, snareNoiseHz:3600, hatHz:9800, hatDecay:0.055, noiseColor:1.0, percRatio:1.72 },
};
function makeDriveCurve(amount:number){ const k=clamp(amount,0.5,8); const samples=1024; const curve=new Float32Array(samples); for(let i=0;i<samples;i+=1){ const x=(i/(samples-1))*2-1; curve[i]=Math.tanh(x*k);} return curve; }
function createNoiseBuffer(audioCtx: AudioContext){ const length=audioCtx.sampleRate; const buffer=audioCtx.createBuffer(1,length,audioCtx.sampleRate); const data=buffer.getChannelData(0); for(let i=0;i<length;i+=1){ const white=Math.random()*2-1; data[i]=white*(0.6+Math.random()*0.4);} return buffer; }
const applySoftTransient=(gain:GainNode,time:number,peak:number,attack:number,release:number)=>{ const safePeak=Math.max(0.0002,peak); gain.gain.cancelScheduledValues(time); gain.gain.setValueAtTime(0.0001,time); gain.gain.linearRampToValueAtTime(safePeak,time+Math.max(0.0012,attack)); gain.gain.setTargetAtTime(0.0001,time+Math.max(0.0012,attack),Math.max(0.004,release)); };
const resolveStyle=(style?:Partial<DrumStyle>):DrumStyle=>({ edge: clamp(style?.edge ?? DEFAULT_DRUM_STYLE.edge,0,1), softness: clamp(style?.softness ?? DEFAULT_DRUM_STYLE.softness,0,1), air: clamp(style?.air ?? DEFAULT_DRUM_STYLE.air,0,1), snap: clamp(style?.snap ?? DEFAULT_DRUM_STYLE.snap,0,1), swing: clamp(style?.swing ?? DEFAULT_DRUM_STYLE.swing,0,1), });
export function createDrumMachine(audioCtx: AudioContext, output: AudioNode): DrumMachine {
  const noiseBuffer=createNoiseBuffer(audioCtx);
  const makeNoiseSource=()=>{ const noise=audioCtx.createBufferSource(); noise.buffer=noiseBuffer; return noise; };
  const triggerKick=(time:number, level:number, kit:DrumKit, style:DrumStyle)=>{ const profile=KIT_PROFILE[kit]; const osc=audioCtx.createOscillator(); const body=audioCtx.createGain(); const clickNoise=makeNoiseSource(); const clickFilter=audioCtx.createBiquadFilter(); const clickGain=audioCtx.createGain(); const sum=audioCtx.createGain(); const shaper=audioCtx.createWaveShaper(); const tone=audioCtx.createBiquadFilter(); osc.type=kit === "glass_metal" ? "triangle" : "sine"; osc.connect(body); body.connect(sum); clickNoise.connect(clickFilter); clickFilter.connect(clickGain); clickGain.connect(sum); sum.connect(shaper); shaper.connect(tone); tone.connect(output); const kickDrive=profile.kickDrive*lerp(0.78,1.22,style.edge); const decay=profile.kickDecay*lerp(1.18,0.84,style.snap)*lerp(1.16,0.9,1-style.softness); shaper.curve=makeDriveCurve(kickDrive); tone.type="lowpass"; tone.frequency.setValueAtTime(profile.kickPitchStart*lerp(5.4,6.8,style.air),time); tone.frequency.exponentialRampToValueAtTime(Math.max(140, profile.kickPitchEnd*lerp(6.2,7.6,style.air)), time+decay); osc.frequency.setValueAtTime(profile.kickPitchStart,time); osc.frequency.exponentialRampToValueAtTime(profile.kickPitchEnd,time+decay); body.gain.setValueAtTime(Math.max(0.0001,level),time); body.gain.exponentialRampToValueAtTime(0.0001,time+decay); clickFilter.type="highpass"; clickFilter.frequency.setValueAtTime(1500+kickDrive*220+style.air*700,time); clickGain.gain.setValueAtTime(level*lerp(0.08,0.22,style.snap),time); clickGain.gain.exponentialRampToValueAtTime(0.0001,time+lerp(0.024,0.012,style.snap)); osc.start(time); osc.stop(time+decay+0.02); clickNoise.start(time); clickNoise.stop(time+0.02); };
  const triggerSnare=(time:number, level:number, kit:DrumKit, style:DrumStyle)=>{ const profile=KIT_PROFILE[kit]; const bodyOsc=audioCtx.createOscillator(); const bodyGain=audioCtx.createGain(); const noise=makeNoiseSource(); const noiseBand=audioCtx.createBiquadFilter(); const noiseHigh=audioCtx.createBiquadFilter(); const noiseGain=audioCtx.createGain(); const shaper=audioCtx.createWaveShaper(); const outGain=audioCtx.createGain(); bodyOsc.type=kit === "membrane_box" ? "sine" : "triangle"; bodyOsc.connect(bodyGain); bodyGain.connect(shaper); noise.connect(noiseBand); noiseBand.connect(noiseHigh); noiseHigh.connect(noiseGain); noiseGain.connect(shaper); shaper.connect(outGain); outGain.connect(output); shaper.curve=makeDriveCurve(lerp(1.05,2.1,(style.edge+style.snap)*0.5)); bodyOsc.frequency.setValueAtTime(profile.snareToneHz*lerp(0.92,1.12,style.snap),time); bodyOsc.frequency.exponentialRampToValueAtTime(profile.snareToneHz*lerp(0.5,0.72,style.softness), time+lerp(0.08,0.13,style.softness)); bodyGain.gain.setValueAtTime(level*lerp(0.18,0.34,style.snap),time); bodyGain.gain.exponentialRampToValueAtTime(0.0001,time+lerp(0.08,0.14,style.softness)); noiseBand.type="bandpass"; noiseBand.frequency.setValueAtTime(profile.snareNoiseHz*lerp(0.82,1.18,style.air),time); noiseBand.Q.setValueAtTime(0.7+profile.noiseColor*0.75+style.snap*0.3,time); noiseHigh.type="highpass"; noiseHigh.frequency.setValueAtTime(1100+profile.noiseColor*700+style.air*1200,time); noiseGain.gain.setValueAtTime(level*lerp(0.42,0.78,style.edge),time); noiseGain.gain.exponentialRampToValueAtTime(0.0001,time+lerp(0.21,0.12,style.snap)); outGain.gain.setValueAtTime(1,time); outGain.gain.exponentialRampToValueAtTime(0.0001,time+lerp(0.28,0.18,style.snap)); bodyOsc.start(time); bodyOsc.stop(time+0.16); noise.start(time); noise.stop(time+0.2); };
  const triggerHat=(time:number, level:number, kit:DrumKit, style:DrumStyle, open=false)=>{ const profile=KIT_PROFILE[kit]; const noise=makeNoiseSource(); const hp=audioCtx.createBiquadFilter(); const bp=audioCtx.createBiquadFilter(); const lp=audioCtx.createBiquadFilter(); const metallicA=audioCtx.createOscillator(); const metallicB=audioCtx.createOscillator(); const metallicGain=audioCtx.createGain(); const sum=audioCtx.createGain(); const shaper=audioCtx.createWaveShaper(); const gain=audioCtx.createGain(); noise.connect(hp); hp.connect(bp); bp.connect(lp); lp.connect(sum); metallicA.type=kit === "glass_metal" ? "triangle" : "square"; metallicB.type="triangle"; metallicA.connect(metallicGain); metallicB.connect(metallicGain); metallicGain.connect(sum); sum.connect(shaper); shaper.connect(gain); gain.connect(output); const bodyHz=profile.hatHz*lerp(0.78,1.14,style.air)*(open ? 0.92 : 0.84); hp.type="highpass"; hp.frequency.setValueAtTime(bodyHz*lerp(0.5,0.7,style.air),time); bp.type="bandpass"; bp.frequency.setValueAtTime(bodyHz,time); bp.Q.setValueAtTime(lerp(0.55,0.95,style.edge)*(open ? 0.9 : 1.0),time); lp.type="lowpass"; lp.frequency.setValueAtTime(Math.min(12000, bodyHz*lerp(0.95,1.32,style.air)*(open ? 1.12 : 1.0)),time); lp.Q.setValueAtTime(0.25+style.edge*0.12,time); metallicA.frequency.setValueAtTime(bodyHz*0.43,time); metallicB.frequency.setValueAtTime(bodyHz*0.57,time); applySoftTransient(metallicGain,time,level*lerp(0.04,0.12,style.edge)*(kit === "glass_metal" ? 1.15 : 1), lerp(0.0032,0.0012,style.snap), open ? lerp(0.042,0.02,style.snap) : lerp(0.026,0.012,style.snap)); shaper.curve=makeDriveCurve(lerp(0.72,1.8,style.edge)); applySoftTransient(gain,time,level*(open ? 0.2 : 0.15)*lerp(0.85,1.12,style.air), lerp(0.0034,0.0012,1-style.softness), open ? profile.hatDecay*lerp(1.18,0.76,style.snap) : profile.hatDecay*lerp(0.92,0.55,style.snap)); noise.start(time); noise.stop(time+(open ? 0.14 : 0.065)); metallicA.start(time); metallicB.start(time); metallicA.stop(time+(open ? 0.14 : 0.065)); metallicB.stop(time+(open ? 0.14 : 0.065)); };
  const triggerClap=(time:number, level:number, kit:DrumKit, style:DrumStyle)=>{ const profile=KIT_PROFILE[kit]; [0,0.012,0.024].forEach((offset,idx)=>{ const noise=makeNoiseSource(); const hp=audioCtx.createBiquadFilter(); const gain=audioCtx.createGain(); noise.connect(hp); hp.connect(gain); gain.connect(output); hp.type="highpass"; hp.frequency.setValueAtTime(profile.snareNoiseHz*0.75+idx*120+style.air*300, time+offset); applySoftTransient(gain,time+offset,level*(0.12-idx*0.024)*lerp(0.9,1.15,style.snap), lerp(0.0022,0.0012,style.snap), lerp(0.034,0.018,style.snap)); noise.start(time+offset); noise.stop(time+offset+0.08); }); };
  const triggerPerc=(time:number, level:number, kit:DrumKit, style:DrumStyle)=>{ const profile=KIT_PROFILE[kit]; const osc=audioCtx.createOscillator(); const filter=audioCtx.createBiquadFilter(); const gain=audioCtx.createGain(); osc.type=kit === "glass_metal" ? "triangle" : "sine"; osc.connect(filter); filter.connect(gain); gain.connect(output); filter.type="bandpass"; filter.frequency.setValueAtTime(520*profile.percRatio*lerp(0.88,1.2,style.air),time); filter.Q.setValueAtTime(3.8+style.edge*1.4,time); osc.frequency.setValueAtTime(280*profile.percRatio,time); osc.frequency.exponentialRampToValueAtTime(180*profile.percRatio, time+lerp(0.1,0.07,style.snap)); gain.gain.setValueAtTime(level*lerp(0.18,0.28,style.snap),time); gain.gain.exponentialRampToValueAtTime(0.0001,time+lerp(0.12,0.08,style.snap)); osc.start(time); osc.stop(time+0.09); };
  const trigger=(voice:DrumVoice,time:number,level:number,kit:DrumKit,styleInput?:Partial<DrumStyle>)=>{ const style=resolveStyle(styleInput); const v=clamp(level,0,1.5); if(v<=0.0001) return; switch(voice){ case "kick": triggerKick(time,v,kit,style); break; case "snare": triggerSnare(time,v,kit,style); break; case "hat_closed": triggerHat(time,v,kit,style,false); break; case "hat_open": triggerHat(time,v,kit,style,true); break; case "clap": triggerClap(time,v,kit,style); break; case "perc": triggerPerc(time,v,kit,style); break; }};
  const schedulePattern=(pattern:DrumPattern,step:number,time:number,level:number,kit:DrumKit,styleInput?:Partial<DrumStyle>)=>{ const style=resolveStyle(styleInput); const softSwing=0.004+style.swing*0.018; const late=time+softSwing; const early=Math.max(0,time-softSwing*0.45); const triggers=getStaticDrumStepTriggers(pattern,step); if(!triggers.length) return; triggers.forEach((entry)=>{ const when=entry.timing === "late" ? late : entry.timing === "early" ? early : time; const voice=entry.laneId === "hatClosed" ? "hat_closed" : entry.laneId === "hatOpen" ? "hat_open" : entry.laneId; trigger(voice,when,level*(entry.levelMultiplier ?? 1),kit,style); }); };
  return { trigger, schedulePattern };
}
